// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umwpyrhtikyappilarbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtd3B5cmh0aWt5YXBwaWxhcmJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3NTE5MzIsImV4cCI6MjA1MDMyNzkzMn0.IEUcxFKHZua_vgbPNzwkqoVMbf3NWKzYOuNr7x7uopw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);